create table public.tasks (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    title text not null,
    is_completed boolean default false not null,
    inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.tasks enable row level security;

-- RLS Policies for the 'tasks' table

-- 1. Users can see their own tasks
create policy "Enable read access for own users"
on public.tasks for select
using (auth.uid() = user_id);

-- 2. Users can insert their own tasks
create policy "Enable insert for own users"
on public.tasks for insert
with check (auth.uid() = user_id);

-- 3. Users can update their own tasks
create policy "Enable update for own users"
on public.tasks for update
using (auth.uid() = user_id);

-- 4. Users can delete their own tasks
create policy "Enable delete for own users"
on public.tasks for delete
using (auth.uid() = user_id);